ci: check for makeappx.exe in windows build

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -179,9 +179,12 @@ jobs:
     runs-on: windows-latest
     needs: setup
     steps:
-      - name: Install Windows SDK
+      - name: Install Windows ADK
+        run: choco install windows-adk -y
+
+      - name: Check makeappx (debug purpose only)
         run: |
-          choco install windows-sdk-10-version-2004-all -y
+          where makeappx.exe || echo "makeappx not found"
 
       - name: Checkout
         uses: actions/checkout@v4
